♻️ 코드 리펙토리:  게임 엔티티 , 게임 서비스 , 게임리퍼토지리 UUID 수정
KMBBJ/KMBBJ_BACKEND pull request #71
Opened 2024-08-21 05:47 UTC by kimkganghyun

게임 엔티티 , 게임 서비스 , 게임리퍼토지리 UUID 수정 

데이터 베이스도 수정

2024-08-21 06:00 UTC, parkswon1 requested changes
변경 점이 많아 보입니다.

2024-08-21 06:00 UTC, parkswon1 commented on backend/src/main/java/com/kmbbj/backend/games/entity/Game.java
> +    @Column(name = "enum", nullable = false)
여기 nullable말고 default도 추가했음 좋겠습니다 게임이 시작되면 자동으로 ACTIVATE시키는건 어떤가요

2024-08-21 06:00 UTC, parkswon1 commented on backend/src/main/java/com/kmbbj/backend/games/service/game/GameServiceImpl.java
> +//            // 마지막 라운드 도달할 때까지 계속 라운드를 진행
여기에 스케줄러로 변경했다고했는데 스케쥴러 코드는 어디에 있나요?

2024-08-21 06:00 UTC, parkswon1 commented on backend/src/main/java/com/kmbbj/backend/games/service/game/GameServiceImpl.java
> +//                } catch (Exception ex) {
예외 처리가 잘못됐습니다

2024-08-21 06:00 UTC, parkswon1 commented on backend/src/main/java/com/kmbbj/backend/games/service/game/GameServiceImpl.java
> +//            throw e; // 예외를 다시 던져 트랜잭션을 롤백하도록 처리
예외처리가 잘못됐습니다.

2024-08-21 06:00 UTC, parkswon1 commented on backend/src/main/java/com/kmbbj/backend/games/controller/GameController.java
> +        CustomResponse<GameStatusDTO> response = new CustomResponse<>(HttpStatus.OK, "게임 시작 성공", gameStatus);
CustomResponse<GameStatusDTO> response = new CustomResponse<>(HttpStatus.OK, "게임 시작 성공", gameStatus);
이렇게 객체를 생성해서 넣지말고
return ResponseEntity.ok().body(new CustomResponse<>(HttpStatus.OK, "게임 시작 성공", gameStatus));
바로 넣는게 더 좋을것 같습니다

2024-08-21 06:00 UTC, parkswon1 commented on backend/src/main/java/com/kmbbj/backend/games/controller/GameController.java
> +    @GetMapping("/{encryptedGameId}/current-round")
path로 받아오게되면 혹시라도 어떤 권한이 없는 사람이 encryptedGameId를 임의로 입력했는데 들어가지는거 아닌가요?

2024-08-21 06:03 UTC, kimkganghyun commented on backend/src/main/java/com/kmbbj/backend/games/service/game/GameServiceImpl.java
> +//            // 마지막 라운드 도달할 때까지 계속 라운드를 진행
스케줄러 아직 미정입니다 코인 객체 받아오면 구현할 예정입니다.

2024-08-21 06:03 UTC, kimkganghyun commented on backend/src/main/java/com/kmbbj/backend/games/entity/Game.java
> +    @Column(name = "enum", nullable = false)
네 알겠습니다

2024-08-21 06:04 UTC, kimkganghyun commented on backend/src/main/java/com/kmbbj/backend/games/service/game/GameServiceImpl.java
> +//                } catch (Exception ex) {
네 참고하겠습니다

2024-08-21 06:23 UTC, kimkganghyun commented on backend/src/main/java/com/kmbbj/backend/games/service/game/GameServiceImpl.java
> +//            throw e; // 예외를 다시 던져 트랜잭션을 롤백하도록 처리
네 참고하겠습니다

2024-08-21 06:27 UTC, kimkganghyun commented on backend/src/main/java/com/kmbbj/backend/games/controller/GameController.java
> +        CustomResponse<GameStatusDTO> response = new CustomResponse<>(HttpStatus.OK, "게임 시작 성공", gameStatus);
감사합니다 변경했습니다

2024-08-21 11:33 UTC, kimkganghyun commented on backend/src/main/java/com/kmbbj/backend/games/controller/GameController.java
> +    @GetMapping("/{encryptedGameId}/current-round")
Path 변수로 encryptedGameId를 받을 때의 보안 위험하고 권한 없는 사용자의 임의 접근 가능성 있을 수 있네요
이를 해결 방안은 방 참여한 사람만 접근 제어 추가 할 예정이고  방에 들어간 사람만 허락 방에 못들어간사람은 접근권한없도록 코드 작성할 예정입니다.

2024-08-22 00:28 UTC, jeayoung98 requested changes
모든 응답 처리가 ResponseEntity<CustomResponse<?>> 이런식으로 되어있는데 코드 통일을 위해서 CustomResponse<?> 이런식으로 바꾸는건 어떨까요

2024-08-22 05:07 UTC, minseoBae submitted a review, later dismissed
응답이랑 예외 처리만 통일해주셨으면 좋겠습니다

2024-08-22 07:07 UTC, hashi285 submitted a review, later dismissed
열심히 하시네요 항상 배웁니다 수고하셨어용

2024-08-23 01:16 UTC, parkswon1 commented
git wiki를 다시 읽어보셔야 할것같습니다

2024-08-23 01:31 UTC, parkswon1 commented on backend/src/main/java/com/kmbbj/backend/games/controller/GameController.java
> +            return new CustomResponse<>(HttpStatus.FORBIDDEN, "이 게임의 상태를 조회할 권한이 없습니다.", null);
저희 예외처리 이런식으로 하지 않기로했자나요 확인해주세요

2024-08-23 01:42 UTC, parkswon1 approved these changes
왠만하면 예외처리나 로직같은건 서비스로직에서 하는게 좋긴한데 뭐 고생하셨습니다. 주석을 좀더 많이 신경써주셨으면 좋겠네요

2024-08-23 01:43 UTC, kimkganghyun commented
> 왠만하면 예외처리나 로직같은건 서비스로직에서 하는게 좋긴한데 뭐 고생하셨습니다. 주석을 좀더 많이 신경써주셨으면 좋겠네요

감사합니다!!!

2024-08-23 02:01 UTC, hashi285 approved these changes
수고하셨습니당

2024-08-23 05:43 UTC, minseoBae approved these changes
고생많으셨습니다

2024-08-23 14:55 UTC, merged