✨ Admin main page / 공지 저장 기능 +  사용자 정보 창 구현
KMBBJ/KMBBJ_BACKEND pull request #72
Opened 2024-08-21 11:26 UTC by hashi285

2024-08-22 00:22 UTC, parkswon1 approved these changes
간단한 답변 부탁드립니다

2024-08-22 00:22 UTC, parkswon1 commented on backend/src/main/java/com/kmbbj/backend/admin/controller/AdminController.java
> +                .body(response); // 바디에 결과 추가
재영님 응답을 보내는방식을 이렇게 해도 상관없나요??

2024-08-22 00:22 UTC, parkswon1 commented on backend/src/main/java/com/kmbbj/backend/admin/service/AdminService.java
> +            throw new ApiException(ExceptionEnum.INTERNAL_SERVER_ERROR); // 저장 중 예외 발생 시
좀더 구제적인 에러를 발생시키면 좋을것 같습니다

2024-08-22 05:10 UTC, minseoBae approved these changes
확인햇습니당

2024-08-22 05:10 UTC, jeayoung98 requested changes
응답처리 바꿔주세요 !

2024-08-22 05:10 UTC, jeayoung98 commented on backend/src/main/java/com/kmbbj/backend/admin/controller/AdminController.java
> +                .body(response); // 바디에 결과 추가
바꿔주세용 return new CustomResponse<>(HttpStatus.OK, "유저 리스트 조회 성공", result); 이렇게만 들어가면 됩니다 !

2024-08-22 05:10 UTC, jeayoung98 commented on backend/src/main/java/com/kmbbj/backend/admin/controller/AdminController.java
> +                .body(response); // 바디에 결과 추가
헤더가 들어가면 저렇게 하기로 했었는데 지금 헤더가 없어졌으니까 통일해주세용

2024-08-22 11:47 UTC, hashi285 commented on backend/src/main/java/com/kmbbj/backend/admin/controller/AdminController.java
> +                .body(response); // 바디에 결과 추가
응애 수정했습니다

2024-08-22 14:56 UTC, jeayoung98 approved these changes
lgtm!

2024-08-23 00:13 UTC, parkswon1 approved these changes
LGTM

2024-08-23 00:13 UTC, minseoBae approved these changes

2024-08-23 00:40 UTC, kimkganghyun approved these changes
확인했습니다 항상 배우고갑니다

2024-08-23 00:43 UTC, merged