⏪	변경 내용 되돌리기 : 게임 UUID 암호화 기능 재적용
KMBBJ/KMBBJ_BACKEND pull request #82
Opened 2024-08-23 17:02 UTC by kimkganghyun

2024-08-26 04:29 UTC, jeayoung98 requested changes
확인부탁드릴게요

2024-08-26 04:29 UTC, jeayoung98 commented on backend/src/main/java/com/kmbbj/backend/games/controller/GameController.java
> +        return new CustomResponse<>(HttpStatus.OK, "게임 종료 성공", "게임이 성공적으로 종료되었습니다.");
응답이 저게 뭐죠 ..?
데이터 전송할게 없으면 null 써놓자고 약속했잖아요.
뭐 저렇게 해도 오류나거나 하지는 않겠지만 통일하기로 했으니 수정부탁드려요

2024-08-26 04:29 UTC, jeayoung98 commented on backend/src/main/java/com/kmbbj/backend/games/service/round/RoundServiceImpl.java
> +        // 다음 라운드 번호가 이미 존재하는지 확인
55번째 줄에서 확인을 했는데 왜 또 확인을 하나요 ??

2024-08-26 08:39 UTC, jeayoung98 approved these changes

2024-08-26 11:48 UTC, parkswon1 submitted a review, later dismissed
이번에는 버그가 없길바랍니다 ㅠㅠㅠㅠ

2024-08-26 11:50 UTC, hashi285 submitted a review, later dismissed
확인했습니당

2024-08-26 12:36 UTC, minseoBae approved these changes
확인했습니다~

2024-08-27 01:41 UTC, jeayoung98 approved these changes
lgtm !

2024-08-27 01:42 UTC, parkswon1 approved these changes
난~ 믿어요!

2024-08-27 04:30 UTC, minseoBae approved these changes
확인했습니당

2024-08-27 05:00 UTC, hashi285 approved these changes
확인했슴니당

2024-08-27 05:00 UTC, merged